[project]
authors = ["Kunal"]
entry = "main.sw"
license = "Apache-2.0"
name = "WeightCompression"

[dependencies]
FixedPoint = { path = "../../../sway-utils/contracts/math/FixedPoint" }
BalancerErrors = { path = "../../../sway-utils/contracts/helpers/BalancerErrors"}